server:
  port: 8081
spring:
  datasource:
    password: 1234
    username: root
    url: jdbc:mysql://192.168.0.105:3306/trade?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: trade-order
goods-url: trade-goods
user-url: trade-user
nacos:
  discovery:
    server-addr: 192.168.0.105:8848
    auto-register: true
mq:
  order:
    consumer:
      group:
        name: order_orderTopic_cancel_group
    topic: orderTopic
    tag:
      cancel: order_cancel
rocketmq:
  producer:
    group: orderProducergroup
  name-server: 192.168.0.104:9876;192.168.0.105:9876
