server:
  port: 8083
host:
  192.168.0.106
spring:
  datasource:
    password: 1234
    username: root
    url: jdbc:mysql://192.168.0.105:3306/trade?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: trade-user
  redis:
    host: 192.168.0.105
    port: 6379
    password:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
#nacos:
#  discovery:
#    server-addr: 192.168.0.105:8848
#    auto-register: true